#########################################################################
#                                                                       #
# This version of the application.yml is used by the Kochiku test suite #
#                                                                       #
#########################################################################

# The descriptions for these settings are in config/application.dev.yml

sender_email_address: 'kochiku@example.com'
kochiku_notifications_email_address: 'kochiku-notifications@example.com'
domain_name: 'example.com'
use_https: false
kochiku_host: 'kochiku.example.com'
git_pair_email_prefix: 'github'
smtp_server: 'localhost'
redis_host: '127.0.0.1'

git_servers:
  github.com:
    type: github
  git.example.com:
    type: github
  git.squareup.com:
    type: github
  stash.example.com:
    type: stash

worker_thresholds:
  minimum_total_workers: 50
  maximum_total_workers: 500
  instance_chunk_size: 10
  number_of_samples: 30
  idle_excess_count: 50
  idle_insufficient_count: 30
  worker_fluctuation_tolerance: 5
  spin_up_script: /path/to/new-instance.rb
  autosize_queue: developer
